### PR TITLE
updated maturin version and ccargo build to build yml

### LINKED ISSUE #1135: Fix Issue with maturin Cargo.lock file
**Describe the bug**
image

Issue in build pipeline found on #1134 
**To Reproduce**
Run the build pipeline after python changes

**Expected behavior**
Expected that build pass with no maturin issues.

**Additional context**
Discovered in build pipeline when updating github for building python wheels.

### PR DESCRIPTION
**Pull request by tbar4**
# Which issue does this PR close?

Closes #1135 

 # Rationale for this change

This change will allow us to create python wheel files for several different platforms. 

# What changes are included in this PR?

A github build file for python wheels will be added and we will also be updating maturin from 0.6.0 t0 1.6.0

# Are there any user-facing changes?

There are no user facing changes

### CODE REVIEW

**Comment by tbar4** [comment]
@andygrove I will tried to get the rest of the jobs fixed tomorrow.

**Comment by tbar4** [comment]
@andygrove checks passed, had to remove maturin github action and manually implement because it couldn't resolve `protoc` because it is not available in the maturin action

**Comment by tbar4** [comment]
@andygrove @milenkovicm update python requirement to align with #1141 of python >=3.7

**Review by andygrove — APPROVED** [review]
Thanks @tbar4! Much appreciated.

**Pull request merged**
