### PR TITLE
Replace BallistaContext with SessionContext

### LINKED ISSUE #1081: Replace `BallistaContext` with `SessionContext`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As we tend to reduce code footprint I would like to propose to replace `BallistaContext` with `SessionContext`.

It would definitely improve usability as we would get most of the methods available in SessionContext also, some DataFusion applications would be deployable to Ballista with single line change.

```rust
use ballista::{extension::SessionContextExt, prelude::*};
use datafusion::prelude::SessionContext;

let ctx : SessionContext = SessionContext::ballista_standalone().await?;
```

With write sinks now in place, we will get write support as well, feature Ballista did not have before.

IMHO it would make a lot of sense to have a single api across DataFusion and Ballista.

If replacement is  successful it would enable us to re-use Datafusion Python crate, eliminating need for maintenance
of Ballista Python, We would need to provide `SessionContext::ballista_standalone` and equivalent methods.

```python
import datafusion
import ballista.standalone
from datafusion import col

# create a context (datafusion context with ballista standalone enabled)
ctx = ballista.standalone.SessionContext()
```

There are clear benefits of deprecation of `BallistaContext`, however decision may be problematic as we could not hide `SessionContext`
methods which do not work with ballista. `SessionContext` may bring usability issues with UDF support, configuration and basically all functionalities which need to be propagated across the cluster to work, and which may not be trivial to address. We may try to be address the by "turning off" those methods in ballista or just by documenting it, still some effort is needed. Or maybe its not issue at all?

**Describe the solution you'd like**

Rough action plan:

- Create `SessionContextExt` which would expose methods for creating `standalone` nad `remote` context, re-using `BallistaQueryPlanner`.
- Verify basic `SQL` and `DataFrame`  support.
- Verify/fix write support (plans with write Sink are generated but write operation does not create valid files).
- Update python crate to create SessionContextExt.
- Deprecate `BallistaContext`.
- Deprecate ballista python.

**Describe alternatives you've considered**

**Additional context**

relates to #1068

### PR DESCRIPTION
**Pull request by milenkovicm**
# Which issue does this PR close?

Closes #1081.

 # Rationale for this change

# What changes are included in this PR?

This PR proposes to replace `BallistaContext` with `SessionContext`.
It provides `SessionContextExt` which adds `standalone*` and `remote*` methods to `SessionContext`,
they set up `SessionContext` in the same way `BallistaContext` does, utilizing `BallistaQueryPlanner`.

standalone connection is optional, can be enabled with `standalone` feature:

```rust
use ballista::prelude::SessionContextExt;
use datafusion::prelude::SessionContext;

let ctx: SessionContext = SessionContext::standalone().await?;
```

to connect to remote cluster

```rust
use ballista::prelude::SessionContextExt;
use datafusion::prelude::SessionContext;

let ctx: SessionContext = SessionContext::remote("localhost",5000).await?;
```

Also there are `SessionContext::remote|local_with_config` methods.

With `SessionContext` extension we finally can run distributed write on ballista cluster.
Also, `BallistaQueryPlanner` has changes slightly to support local `information_schema` queries,
`BallistaQueryPlanner` will detect scans against local catalogs tables and run it at current context.

```rust
use ballista::prelude::SessionContextExt;
use datafusion::prelude::SessionContext;

let ctx: SessionContext = SessionContext::standalone_with_config(&config).await?;

let result = ctx
    .sql("select name from information_schema.df_settings where name like 'datafusion.%' order by name limit 5")
    .await?
    .collect()
    .await?;

let expected = vec![
    "+------------------------------------------------------+",
    "| name                                                 |",
    "+------------------------------------------------------+",
    "| datafusion.catalog.create_default_catalog_and_schema |",
    "| datafusion.catalog.default_catalog                   |",
    "| datafusion.catalog.default_schema                    |",
    "| datafusion.catalog.format                            |",
    "| datafusion.catalog.has_header                        |",
    "+------------------------------------------------------+",
];

assert_batches_eq!(expected, &result);
```

There are tests covering added functionality but also test ported from `BallistaContext` passing (actually one was fixed
as there was no support to `SHOW` queries).

There are few unsupported functionalities that I stumble upon:

- `DataFrame.cache()` does not work
- `EXPLAIN` query does not resolve correct plan
- `DML` not supported (as node can't be serialized)
- ...

If this PR is to be merged I'll try to update Ballista python to support it (or someone else can).
After which we can open discussion if we want to deprecate `BallistaContext`.

As follow up (new tasks)

- `BallistaConfiguration` needs some attention, not sure if there are configuration properties which are shared with ballista
- SessionContext configuration to be shared across cluster
- `SessionState` to be exposed as construction parameter in client and executor (not sure about scheduler), which would remove need for object store creation.

# Are there any user-facing changes?

New public interface, no changes to previous api

### CODE REVIEW

**Comment by milenkovicm** [comment]
At the moment this just a draft, need a bit more work.
Looks like we finally support write in ballista, if we use `SessionContext` directly.
It looks a bit easy, do I miss something @andygrove ?

**Comment by andygrove** [comment]
> It looks a bit easy, do I miss something @andygrove ?

I quickly skimmed over this and I thought it looks good.

**Comment by milenkovicm** [comment]
thanks @andygrove , 
I'm almost happy with current state of the PR, we have distributed write and `information_schema` support as new features.
Will try to use new methods to initialise PySessionContext and provide initial support for datafusion python.

**Comment by milenkovicm** [comment]
when ever you have time @andygrove please have a look, 
I haven't done any changes to python interface as of yet, as it would make this PR too big.
there is some duplicate code which can be re-used, will be addressed as follow up

**Comment by milenkovicm** [comment]
did a quick test for python support

```python
from datafusion.context import SessionContext
from pyballista import Ballista

# this makes most of the ballista python code redundant 
ctx : SessionContext = Ballista.standalone()

df = ctx.sql("SELECT 1")
batches = df.collect()
batches.show()

df = ctx.sql("SHOW TABLES").show()
ctx.register_parquet("p", "testdata/test.parquet")

ctx.sql("select * from p").show()
ctx.sql("select name, value from information_schema.df_settings where name like 'ballista%'").show()
```

**Comment by milenkovicm** [comment]
two things left to be addressed 
- remote to get url instead of host, port tuple
- do not expose `_with_config` as we may be able to deprecate `BallistaConfig` as well

**Review by andygrove — APPROVED** [review]
This looks amazing. Thank you @milenkovicm

**Comment by milenkovicm** [comment]
thanks a lot @andygrove 
will push few small changes, and fix test asap 

i'll use url in remote methods as may help add security later, and I'll remove methods with `config` as im not sure about them, will add them in due course once i get better idea about configuration (would not be great to add them then remove them :) )

**Comment by milenkovicm** [comment]
can't really fix failing test on windows, disabling it for now on windows.
clippy should be fixed with #1090

**Comment by milenkovicm** [comment]
I'm happy with current PR state, will create follow up PRs for configuration, python, and to try windows test.
@andygrove  If you're happy with the PR please merge it after #1090 which should fix clippy issues

**Comment by milenkovicm** [comment]
thanks a lot @andygrove

**Pull request merged**
