### PR TITLE
Remove UI

### PR DESCRIPTION
**Pull request by milenkovicm**
As part of effort outlined in https://github.com/apache/datafusion-ballista/pull/1066 and https://github.com/apache/datafusion-ballista/issues/1067 this PR removes UI package from core ballista.

Relates to: https://github.com/apache/datafusion-ballista/pull/1066 & https://github.com/apache/datafusion-ballista/issues/1067

# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by milenkovicm** [comment]
should be removed now, plus few extra lines i found

**Review by andygrove — APPROVED** [review]
LGTM. Could you fix the merge conflict?

**Comment by milenkovicm** [comment]
done

**Comment by andygrove** [comment]
Looks like there is still a reference in the docker scripts:

```
+ cd ballista/scheduler/ui
/home/builder/builder-entrypoint.sh: line 27: cd: ballista/scheduler/ui: No such file or directory
```

**Pull request merged**
