### PR TITLE
Ballista reloaded - proposed changes to core ballista 

### PR DESCRIPTION
**Pull request by milenkovicm**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

First of all, apologies for a gigantic PR, but I did not see better way of making this proposal.

With this proposal I'd like to propose one way forward for ballista, direction is not set in stone so we could discuss alternatives.

I'd like to set the stage with driving idea, it may help understanding PR better.

I believe if we want to revive ballista we need to make it a library rather than full fledge application with all batteries included. If we continue developing it as an application, core code will just grow, putting maintainers on pressure to maintain code which may not be related to core ballista mission.
Making ballista as library, which could bootstrap schedulers and executors with few lines of code, with possibility to plug in additional functionalities will keep use-case specific code out of ballista. We should make it as simple as bootstrapping datafusion application.

Second goal, I believe,  should be keeping ballista functionalities on par with datafusion releases. At the moment ballista is missing a lot of functionalities, like writes, sinks, to name a few. The main, short term, goal would be to get writes, inserts supported.

Lastly, client-scheduler, and scheduler-executor interaction should be improved. Client-scheduler at the moment communicate using custom made gprc protocol, which could get support for UDF(s), configuration ... current client-scheduler protocol can be made an optional component, so users can bring their own frontend such as spark connect, or similar. scheduler-executor as well can be extended to support session configuration information, ...

So with those high level goals in mind, I have done a bit of code trimming and maintenance. I have removed some code which I personally believe should/could be an "add-on" to ballista. 

# What changes are included in this PR?

This PR removes:

- python support (datafusion python is the main effort, we should focus making it run on ballista)
- helm support (this can be contrib project)
- good part of ci directory (ci works without it)
- plugin sub-system (never finalized)
- caching support (this can be a contrib project)
- support for hdfs (library too old, there are newer library to be used)
- UI (can be a contrib project)
- made keda, rest-api, flight-sql optional (we could move them to contrib project)
- key value store is gone, only memory store remains
- removes some dependencies which were detected as not used

This PR adds no functionality, but updates most of the dependencies.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by andygrove** [comment]
@Dandandan @thinkharderdev @avantgardnerio @yahoNanJing @mingmwang do you have any opinions on this approach?

**Comment by Dandandan** [comment]
I think it makes a lot of sense to reduce the size of Ballista in order to keep maintaining it. I think it also makes sense to move python support to Python DataFusion (to keep same API).
thanks @milenkovicm .

**Comment by Dandandan** [comment]
It would be nice to create a few tickets from this, e.g. supporting ballista in datafusion python, creating a contrib project for the ballista UI, Flight SQL etc.

**Comment by alamb** [comment]
I agree that tracking the change in the overall goal as a ticket would be very helpful -- both for tracking follow on items as @Dandandan says as well as ensuring we have the validation / rationale described

I personally think creating a "extensible distributed query engine" (aka what I think is proposed by this PR) makes a lot of sense 💯

**Comment by thinkharderdev** [comment]
I think it makes a lot of sense

**Comment by milenkovicm** [comment]
One additional thing, I don't think we're too far away from supporting writes in ballista client. Datafusion team did great job with `Sink` support.

```rust
use ballista::ext::BallistaExt;
use datafusion::{execution::options::ParquetReadOptions, prelude::SessionContext};

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    //
    // should we remove BallistaContext ?!
    //
    let ctx = SessionContext::ballista_standalone().await?;

    ctx.register_parquet(
        "test",
        &format!("{testdata}/alltypes_plain.parquet"),
        ParquetReadOptions::default(),
    )
    .await?;

    let df = ctx.sql("select * from test").await?;
    df.write_csv(
        "/directory/to_write/csv",
        Default::default(),
        Default::default(),
    )
    .await?;

    Ok(())
}
```

It does resolve and execute plan, writes the file, but unfortunately file does not make sense (some kind of binary, not sure if it arrow): 

```text
[DEBUG datafusion::physical_planner] Optimized physical plan:
    DataSinkExec: sink=CsvSink(file_groups=[])
      ParquetExec: file_groups={1 group: [[/arrow-ballista/examples/testdata/alltypes_plain.parquet]]}, projection=[id, bool_col, tinyint_col, smallint_col, int_col, bigint_col, float_col, double_col, date_string_col, string_col, timestamp_col]
    
    
[INFO  ballista_scheduler::planner] planning query stages for job m1UAyt4
[INFO  ballista_scheduler::state::task_manager] Submitting execution graph: ExecutionGraph[job_id=m1UAyt4, session_id=e294befd-26ce-4927-b447-e0779a1fcd6f, available_tasks=0, is_successful=false]
    =========ResolvedStage[stage_id=1.0, partitions=1]=========
    ShuffleWriterExec: None
      DataSinkExec: sink=CsvSink(file_groups=[])
        ParquetExec: file_groups={1 group: [[/arrow-ballista/examples/testdata/alltypes_plain.parquet]]}, projection=[id, bool_col, tinyint_col, smallint_col, int_col, bigint_col, float_col, double_col, date_string_col, string_col, timestamp_col]

[INFO  ballista_scheduler::display] === [m1UAyt4/1] Stage finished, physical plan with metrics ===
    ShuffleWriterExec: None, metrics=[output_rows=1, input_rows=1, repart_time=1ns, write_time=19.28307ms]
      DataSinkExec: sink=CsvSink(file_groups=[]), metrics=[output_rows=8, elapsed_compute=1ns, bytes_scanned=671, num_predicate_creation_errors=0, page_index_rows_filtered=0, row_groups_matched_statistics=0, predicate_evaluation_errors=0, row_groups_matched_bloom_filter=0, row_groups_pruned_statistics=0, pushdown_rows_filtered=0, row_groups_pruned_bloom_filter=0, file_open_errors=0, file_scan_errors=0, time_elapsed_opening=13.991107ms, time_elapsed_processing=12.901754ms, time_elapsed_scanning_total=1.801347ms, time_elapsed_scanning_until_data=1.628914ms, page_index_eval_time=2ns, pushdown_eval_time=2ns]
        ParquetExec: file_groups={1 group: [[/arrow-ballista/examples/testdata/alltypes_plain.parquet]]}, projection=[id, bool_col, tinyint_col, smallint_col, int_col, bigint_col, float_col, double_col, date_string_col, string_col, timestamp_col], metrics=[]
```

One question which arise is should we remove `BallistaContext` and use `SessionContext::ballista_standalone().await?`, there are pros and cons for both approaches, I would personally prefer `SessionContext` but I'm afraid there will be unforeseen issues

**Comment by alamb** [comment]
>  Datafusion team did great job with Sink support.

Kudos to @metesynnada and @devindangelo

**Comment by andygrove** [comment]
There seems to be general consensus that this is a good direction.

It would be good to know who is willing to work on this initiative. I imagine that it will require substantial PR review time.

**Comment by metegenez** [comment]
An extensible distributed query engine could be a game-changer for Ballista, as it would reduce the time required to maintain the codebase. Shifting part of the code would be a great step forward, and I can assist with the review process. We’re already in daily discussions with @milenkovicm.

If we reach a consensus on the roadmap in general, we can begin determining which components to remove.

Just a heads-up: @metesynnada is no longer active, so I’m using my personal account now.

**Comment by andygrove** [comment]
@metegenez Could you create an epic for this proposal and then I think others can help with creating inividual issues.

I'd like to see some smaller PRs that get us to the proposal. For example, perhaps removing the UI could be the first PR?

I'm happy to help with reviews but will only be able to work on this at weekends since it isn't a priority for my employer. My main concern is keeping TPC-H running correctly throughout this process (we do not have CI tests yet to prevent regressions, so I test this manually at the moment).

**Comment by andygrove** [comment]
> @metegenez Could you create an epic for this proposal and then I think others can help with creating inividual issues.

Oops, I meant to tag @milenkovicm.

**Comment by milenkovicm** [comment]
also, we could remove deps update commits and cherry pick it to new PR

**Comment by andygrove** [comment]
> Now, this PR has many things removed, but not too many code changed, would you like to take it step by step and re-do this work again or we can just merge this as once off, without squashing commits so we can revert removal if needed @andygrove ? I understand that it is a bit of big PR.

Honestly, this is too big for me to do a comprehensive review within the limited weekend time that I have available. It seems that some very unrelated changes would be easy to split out, so we can start with those first to at least reduce the size of this PR?

For example, these could be separate smaller PRs that would be easy to review:

- Remove UI
- Remove Python
- Remove Helm
- Clean up CI
- Clean up dependencies

We could get through these very quickly, I think.

**Comment by milenkovicm** [comment]
all right, will cherry-pick issue from big branch. I'm doing this at my spare time so bear with me :) 

created #1067  listing all features for removal, and #1068 as high level road map proposal to kick off discussions and ideas.

is it ok just to refer PR to #1067 list or you prefer having issue created for each PR @andygrove

**Comment by andygrove** [comment]
> all right, will cherry-pick issue from big branch. I'm doing this at my spare time so bear with me :)
> 
> created #1067 listing all features for removal, and #1068 as high level road map proposal to kick off discussions and ideas.
> 
> is it ok just to refer PR to #1067 list or you prefer having issue created for each PR @andygrove

That's great. Thank you. No need to create separate issues per item.

**Comment by milenkovicm** [comment]
Thanks all for you comments, I'm closing this PR as most of changes have been done in #1067.
It would be greatly appreciated if you have a read and comment #1068, I'm might take I'm going to break down task and start implementation once we wrap up #1067

**Pull request closed without merging**
